name: 'Terraform Pull Request'

on:
  pull_request:

jobs:
  terraform-plan:
    name: "Terraform Pull Request"
    runs-on: x2-runners #ubuntu-latest
    steps:
      #----------------------------- Setup -------------------------------#
      # Checkout the code
      # Marketplace: https://github.com/marketplace/actions/checkout
      - name: Setup - Checkout
        uses: actions/checkout@v2.1.0

      # Static analysis of Terraform templates to spot potential security issues
      # Marketplace: https://github.com/marketplace/actions/terraform-security-scan
      - name: Setup - Security Scan
        uses: triat/terraform-security-scan@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Configure AWS credential environment variables for use in other GitHub Actions.
      # https://github.com/aws-actions/configure-aws-credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: us-east-1

      # Downloads a specific version of Terraform CLI and adds it to PATH
      # Marketplace: https://github.com/marketplace/actions/hashicorp-setup-terraform
      - name: Setup - Terraform CLI
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.8

      #https://github.com/marketplace/actions/setup-tflint
      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v1
        with:
          tflint_version: latest
          github_token: ${{ secrets.GITHUB_TOKEN }}

      #----------------------------- Action -------------------------------#
      # tflint Folder
      - name: Run TFLint
        run: tflint -f compact
        
      # Terraform fmt
      - name: Terraform Format prod
        id: fmt
        run: terraform fmt -check

      # Terraform init
      - name: Terraform Init
        id: init
        run: terraform init -input=false
        # GIT_SSH_COMMAND: "echo '${{ secrets.GH_SSH }}' > id_rsa
        # && ssh-keyscan github.com > known_hosts
        # && chmod 600 id_rsa known_hosts
        # && ssh -i ./id_rsa -o UserKnownHostsFile=./known_hosts"
        
      # Terraform validate
      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color
        continue-on-error: true
        
      # The id value is used for reference in the comment step via "steps.plan.outputs.stdout"
      # Note: Color is disabled to prevent messy characters from appearing in the pull request comment
      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color
        # GIT_SSH_COMMAND: "echo '${{ secrets.GH_SSH }}' > id_rsa
        # && ssh-keyscan github.com > known_hosts
        # && chmod 600 id_rsa known_hosts
        # && ssh -i ./id_rsa -o UserKnownHostsFile=./known_hosts"
        continue-on-error: true

      # Submit a comment with the plan output to the pull request
      - name: "Run - Terraform Comment"
        uses: actions/github-script@0.9.0
        env:
          STDOUT: "```${{ steps.plan.outputs.stdout }}```"
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const output = `#### Terraform Format and Style \`${{ steps.fmt.outcome }}\`
            #### Terraform Initialization \`${{ steps.init.outcome }}\`
            #### Terraform Validation \`${{ steps.validate.outcome }}\`
            #### Terraform Plan \`${{ steps.plan.outcome }}\`
            <details><summary>Show Plan</summary>
            \`\`\`\n
            ${process.env.PLAN}
            \`\`\`
            </details>
            *Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`*`;
            
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: process.env.STDOUT
            })
            
      # Ensure that if the plan fails, the workflow fails
      - name: Terraform Plan or Validate Status 
        id: tfps
        if: steps.plan.outcome == 'failure' || steps.validate.outcome == 'failure'
        run: exit 1
