name: 'Terraform Apply'
on:
  push:
    branches:
      - master

jobs:
  Terraform-apply:
    name: "Terraform Apply"
    runs-on: ubuntu-latest
    steps:
      #----------------------------- Setup -------------------------------#
      # Checkout the code
      # Marketplace: https://github.com/marketplace/actions/checkout
      - name: Setup - Checkout
        uses: actions/checkout@v2.1.0
        with:
          terraform_version: 1.0.0

      # Configure AWS credential environment variables for use in other GitHub Actions.
      # https://github.com/aws-actions/configure-aws-credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: us-east-1

      # Downloads a specific version of Terraform CLI and adds it to PATH
      # Marketplace: https://github.com/marketplace/actions/hashicorp-setup-terraform
      - name: Setup - Terraform CLI
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.8

      #----------------------------- Action -------------------------------#
      # Terraform init in prod folder
      - name: Terraform Init
        id: init
        run: terraform init -input=false

      # Terraform apply 
      # Auto-approve prevents the requirement of human interaction
      - name: Terraform Apply
        if: github.ref == 'refs/heads/master'
        run: cd prod && terraform apply -input=false -auto-approve
